
on: push
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: "Login to Docker hub"
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Build  to Docker Hub
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/task1
      
    - name: Push  to Docker Hub
      run: docker push  ${{secrets.DOCKER_USERNAME}}/task1
    
